#! /bin/bash
cont=true
bare=""
while $cont && test -n "$1"; do
  case $1 in
    --bare | -b)
      bare=true
      shift;;
    --nobare | -n)
      bare=false
      shift;;
    --help)
      echo "Initializes a remote Git repository over SSH."
      echo "Usage:"
      options="[--bare | --nobare]"
      echo "  $(basename "$0") $options ssh://host.com:22//path/to/repos.git"
      echo "  $(basename "$0") $options ssh://host.com:2222/~user/path/to/repos"
      echo "  $(basename "$0") $options host.com:/path/to/repos"
      echo "  $(basename "$0") $options host.com:~user/path/to/repos.git"
      echo ""
      echo "By default the repositories ending with \".git\" are bare, and all others are not."
      echo "To override the default use --bare (-b) or --nobare (-n)."
      exit;;
    -*)
      echo "Unknown option $1. Run $(basename "$0") --help for help."
      exit 200;;
    *)
      cont=false;;
  esac
done

url="$1"
case $url in
  ssh://*)
    x="${url#ssh://}"
    repos_path="${x#*/}"
    host_n_port="${x%/$repos_path}"
    host="${host_n_port%:*}"
    port="${host_n_port#$host}"
    port="${port#:}"
    ;;
  *:*)
    x="$1"
    repos_path="${x#*:}"
    host="${x%:$repos_path}"
    port=""
    ;;
  *)
    echo "Bad remote repository: $url."
    echo "Accepted are ssh://foo.bar/~/boz and foo.bar:~/boz urls."
    exit
esac

test -n "$bare" || if test "$repos_path" == "${repos_path%.git}"; then bare=false; else bare=true; fi

test -n "$port" || port=22
$bare && git_dir="$repos_path"
$bare || git_dir="$repos_path/.git"
ssh -p $port $host "mkdir -p $repos_path && cd $repos_path && GIT_DIR=$git_dir git-init"
