#! /bin/bash
die() {
    echo "$*"
    exit
}
test -z "$2" && die "usage: $(basename "$0") source-workspace destination-workspace"
src_dir="$1"
dst_dir="$2"
test -d "$src_dir" || die "source workspace must exist, but does not: $src_dir"

mkdir -p "$dst_dir/.metadata"
test -f "$dst_dir/version.ini" || echo "org.eclipse.core.runtime=1" >"$dst_dir/version.ini"

mkdir -p $dst_dir/.metadata/.plugins/org.eclipse.core.runtime/.settings
cp $src_dir/.metadata/.plugins/org.eclipse.core.runtime/.settings/*.prefs $dst_dir/.metadata/.plugins/org.eclipse.core.runtime/.settings/

mkdir -p "$dst_dir/.metadata/.plugins/org.eclipse.ui.workbench"
cp $src_dir/.metadata/.plugins/org.eclipse.ui.workbench/{dialog_settings.xml,workbench.xml} $dst_dir/.metadata/.plugins/org.eclipse.ui.workbench/
